### PR TITLE
Remove unstyled, v1 forecast code

### PR DESCRIPTION
**Pull request by patrickjfl**
## Changes in this PR

This PR removes lots of files and code related to our original, unstyled implementation of airText forecasts. There are also a few tweaks to styling and tests to make sure they still pass. I've had to add some guards to the JS event listener code to prevent the integration tests from failing - if there's anything obvious that I'm missing here, please shout! 

The homepage isn't beautiful, but I think it's fine for our temporary purposes.

### Before

Screenshot 2024-11-06 at 12 32 56

### After

Screenshot 2024-11-06 at 12 32 44

## Next steps

- [ ] Run any necessary
      [accessibility testing](https://playbook.dxw.com/guides/web-accessibility.html)
      on this feature.

### CODE REVIEW

**Comment by patrickjfl** [comment]
[Remove v1 forecast and alerts](https://trello.com/c/xQ3wx6yq/103-remove-v1-forecast-and-alerts)

**Comment by edavey** [comment]
looking good! thanks for tidying up this up this refactoring scaffolding. Should we take the opportunity to also strip out:

- jquery-rails
- bootstrap
- govuk-components

**Review by edavey — APPROVED** [review]
🏅

**Comment by patrickjfl** [comment]
> looking good! thanks for tidying up this up this refactoring scaffolding. Should we take the opportunity to also strip out:
> 
>     * jquery-rails
> 
>     * bootstrap
> 
>     * govuk-components

yes, good idea! have done

**Pull request merged**
